/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GameLeaderboard {
  export type PlayerScoreStruct = {
    player: AddressLike;
    score: BigNumberish;
    timestamp: BigNumberish;
    streakDays: BigNumberish;
  };

  export type PlayerScoreStructOutput = [
    player: string,
    score: bigint,
    timestamp: bigint,
    streakDays: bigint
  ] & { player: string; score: bigint; timestamp: bigint; streakDays: bigint };
}

export interface GameLeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LEADERBOARD_SIZE"
      | "addressToFid"
      | "checkIns"
      | "dailyCheckIn"
      | "fidToAddress"
      | "getCheckInStatus"
      | "getLeaderboard"
      | "getLeaderboardSize"
      | "getPlayerRank"
      | "leaderboard"
      | "linkWallet"
      | "owner"
      | "playerBestScore"
      | "resetLeaderboard"
      | "scoreNonces"
      | "scoreSigner"
      | "setScoreSigner"
      | "submitScore"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyCheckInCompleted"
      | "LeaderboardUpdated"
      | "ScoreSignerUpdated"
      | "ScoreSubmitted"
      | "WalletLinked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_LEADERBOARD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addressToFid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIns",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyCheckIn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fidToAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCheckInStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboardSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "linkWallet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerBestScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scoreNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scoreSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setScoreSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_LEADERBOARD_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToFid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkIns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dailyCheckIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fidToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCheckInStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboardSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "linkWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerBestScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoreNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoreSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setScoreSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DailyCheckInCompletedEvent {
  export type InputTuple = [player: AddressLike, streak: BigNumberish];
  export type OutputTuple = [player: string, streak: bigint];
  export interface OutputObject {
    player: string;
    streak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [
    player: AddressLike,
    score: BigNumberish,
    rank: BigNumberish
  ];
  export type OutputTuple = [player: string, score: bigint, rank: bigint];
  export interface OutputObject {
    player: string;
    score: bigint;
    rank: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSignerUpdatedEvent {
  export type InputTuple = [newSigner: AddressLike];
  export type OutputTuple = [newSigner: string];
  export interface OutputObject {
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    player: AddressLike,
    score: BigNumberish,
    streak: BigNumberish
  ];
  export type OutputTuple = [player: string, score: bigint, streak: bigint];
  export interface OutputObject {
    player: string;
    score: bigint;
    streak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletLinkedEvent {
  export type InputTuple = [fid: BigNumberish, wallet: AddressLike];
  export type OutputTuple = [fid: bigint, wallet: string];
  export interface OutputObject {
    fid: bigint;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameLeaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): GameLeaderboard;
  waitForDeployment(): Promise<this>;

  interface: GameLeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LEADERBOARD_SIZE: TypedContractMethod<[], [bigint], "view">;

  addressToFid: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  checkIns: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        lastCheckIn: bigint;
        streak: bigint;
        hasMissed: boolean;
      }
    ],
    "view"
  >;

  dailyCheckIn: TypedContractMethod<[], [bigint], "nonpayable">;

  fidToAddress: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getCheckInStatus: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, boolean] & {
        lastCheckIn: bigint;
        streak: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [limit: BigNumberish],
    [GameLeaderboard.PlayerScoreStructOutput[]],
    "view"
  >;

  getLeaderboardSize: TypedContractMethod<[], [bigint], "view">;

  getPlayerRank: TypedContractMethod<
    [player: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  leaderboard: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        player: string;
        score: bigint;
        timestamp: bigint;
        streakDays: bigint;
      }
    ],
    "view"
  >;

  linkWallet: TypedContractMethod<[fid: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  playerBestScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  resetLeaderboard: TypedContractMethod<[], [void], "nonpayable">;

  scoreNonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  scoreSigner: TypedContractMethod<[], [string], "view">;

  setScoreSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  submitScore: TypedContractMethod<
    [score: BigNumberish, nonce: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LEADERBOARD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addressToFid"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkIns"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        lastCheckIn: bigint;
        streak: bigint;
        hasMissed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dailyCheckIn"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "fidToAddress"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCheckInStatus"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, boolean] & {
        lastCheckIn: bigint;
        streak: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [GameLeaderboard.PlayerScoreStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboardSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerRank"
  ): TypedContractMethod<[player: AddressLike], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "leaderboard"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        player: string;
        score: bigint;
        timestamp: bigint;
        streakDays: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "linkWallet"
  ): TypedContractMethod<[fid: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerBestScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "resetLeaderboard"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scoreNonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "scoreSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setScoreSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [score: BigNumberish, nonce: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DailyCheckInCompleted"
  ): TypedContractEvent<
    DailyCheckInCompletedEvent.InputTuple,
    DailyCheckInCompletedEvent.OutputTuple,
    DailyCheckInCompletedEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSignerUpdated"
  ): TypedContractEvent<
    ScoreSignerUpdatedEvent.InputTuple,
    ScoreSignerUpdatedEvent.OutputTuple,
    ScoreSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WalletLinked"
  ): TypedContractEvent<
    WalletLinkedEvent.InputTuple,
    WalletLinkedEvent.OutputTuple,
    WalletLinkedEvent.OutputObject
  >;

  filters: {
    "DailyCheckInCompleted(address,uint256)": TypedContractEvent<
      DailyCheckInCompletedEvent.InputTuple,
      DailyCheckInCompletedEvent.OutputTuple,
      DailyCheckInCompletedEvent.OutputObject
    >;
    DailyCheckInCompleted: TypedContractEvent<
      DailyCheckInCompletedEvent.InputTuple,
      DailyCheckInCompletedEvent.OutputTuple,
      DailyCheckInCompletedEvent.OutputObject
    >;

    "LeaderboardUpdated(address,uint256,uint256)": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;

    "ScoreSignerUpdated(address)": TypedContractEvent<
      ScoreSignerUpdatedEvent.InputTuple,
      ScoreSignerUpdatedEvent.OutputTuple,
      ScoreSignerUpdatedEvent.OutputObject
    >;
    ScoreSignerUpdated: TypedContractEvent<
      ScoreSignerUpdatedEvent.InputTuple,
      ScoreSignerUpdatedEvent.OutputTuple,
      ScoreSignerUpdatedEvent.OutputObject
    >;

    "ScoreSubmitted(address,uint256,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;

    "WalletLinked(uint256,address)": TypedContractEvent<
      WalletLinkedEvent.InputTuple,
      WalletLinkedEvent.OutputTuple,
      WalletLinkedEvent.OutputObject
    >;
    WalletLinked: TypedContractEvent<
      WalletLinkedEvent.InputTuple,
      WalletLinkedEvent.OutputTuple,
      WalletLinkedEvent.OutputObject
    >;
  };
}
