/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameLeaderboard } from "./GameLeaderboard";
export * as factories from "./factories";
export { GameLeaderboard__factory } from "./factories/GameLeaderboard__factory";
